"""add_workflow_deps_and_subscriptions

Revision ID: 014a89866b74
Revises: 165c0ccd5de2
Create Date: 2026-03-08 22:46:07.029873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014a89866b74'
down_revision: Union[str, None] = '165c0ccd5de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_workflow_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_workflow_subscriptions_id'), 'paper_workflow_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_paper_workflow_subscriptions_paper_id'), 'paper_workflow_subscriptions', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_workflow_subscriptions_workflow_id'), 'paper_workflow_subscriptions', ['workflow_id'], unique=False)
    op.add_column('todo_items', sa.Column('source_workflow_id', sa.Integer(), nullable=True))
    op.add_column('todo_items', sa.Column('blocked_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_todo_items_source_workflow_id'), 'todo_items', ['source_workflow_id'], unique=False)
    op.create_foreign_key(None, 'todo_items', 'todo_items', ['blocked_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'todo_items', 'workflows', ['source_workflow_id'], ['id'], ondelete='SET NULL')
    op.add_column('workflow_steps', sa.Column('depends_on_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workflow_steps', 'workflow_steps', ['depends_on_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_steps', type_='foreignkey')
    op.drop_column('workflow_steps', 'depends_on_id')
    op.drop_constraint(None, 'todo_items', type_='foreignkey')
    op.drop_constraint(None, 'todo_items', type_='foreignkey')
    op.drop_index(op.f('ix_todo_items_source_workflow_id'), table_name='todo_items')
    op.drop_column('todo_items', 'blocked_by_id')
    op.drop_column('todo_items', 'source_workflow_id')
    op.drop_index(op.f('ix_paper_workflow_subscriptions_workflow_id'), table_name='paper_workflow_subscriptions')
    op.drop_index(op.f('ix_paper_workflow_subscriptions_paper_id'), table_name='paper_workflow_subscriptions')
    op.drop_index(op.f('ix_paper_workflow_subscriptions_id'), table_name='paper_workflow_subscriptions')
    op.drop_table('paper_workflow_subscriptions')
    # ### end Alembic commands ###
