"""add_workflows

Revision ID: 165c0ccd5de2
Revises: 97ad273a8684
Create Date: 2026-03-07 23:19:39.464785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165c0ccd5de2'
down_revision: Union[str, None] = '97ad273a8684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_owner_id'), 'workflows', ['owner_id'], unique=False)
    op.create_table('personal_todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'done', name='todostatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('source_workflow_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_todos_id'), 'personal_todos', ['id'], unique=False)
    op.create_index(op.f('ix_personal_todos_source_workflow_id'), 'personal_todos', ['source_workflow_id'], unique=False)
    op.create_index(op.f('ix_personal_todos_user_id'), 'personal_todos', ['user_id'], unique=False)
    op.create_table('workflow_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=True),
    sa.Column('shared_with_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shared_with_group_id'], ['research_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_shares_id'), 'workflow_shares', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_shares_shared_with_group_id'), 'workflow_shares', ['shared_with_group_id'], unique=False)
    op.create_index(op.f('ix_workflow_shares_shared_with_user_id'), 'workflow_shares', ['shared_with_user_id'], unique=False)
    op.create_index(op.f('ix_workflow_shares_workflow_id'), 'workflow_shares', ['workflow_id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_offset_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_id'), 'workflow_steps', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_steps_workflow_id'), 'workflow_steps', ['workflow_id'], unique=False)
    op.create_table('workflow_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.Enum('paper_status', 'group_join', name='workflowtriggertype'), nullable=False),
    sa.Column('target_status', sa.String(length=32), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['research_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_triggers_group_id'), 'workflow_triggers', ['group_id'], unique=False)
    op.create_index(op.f('ix_workflow_triggers_id'), 'workflow_triggers', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_triggers_workflow_id'), 'workflow_triggers', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_triggers_workflow_id'), table_name='workflow_triggers')
    op.drop_index(op.f('ix_workflow_triggers_id'), table_name='workflow_triggers')
    op.drop_index(op.f('ix_workflow_triggers_group_id'), table_name='workflow_triggers')
    op.drop_table('workflow_triggers')
    op.drop_index(op.f('ix_workflow_steps_workflow_id'), table_name='workflow_steps')
    op.drop_index(op.f('ix_workflow_steps_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_workflow_shares_workflow_id'), table_name='workflow_shares')
    op.drop_index(op.f('ix_workflow_shares_shared_with_user_id'), table_name='workflow_shares')
    op.drop_index(op.f('ix_workflow_shares_shared_with_group_id'), table_name='workflow_shares')
    op.drop_index(op.f('ix_workflow_shares_id'), table_name='workflow_shares')
    op.drop_table('workflow_shares')
    op.drop_index(op.f('ix_personal_todos_user_id'), table_name='personal_todos')
    op.drop_index(op.f('ix_personal_todos_source_workflow_id'), table_name='personal_todos')
    op.drop_index(op.f('ix_personal_todos_id'), table_name='personal_todos')
    op.drop_table('personal_todos')
    op.drop_index(op.f('ix_workflows_owner_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
