"""add author claim requests

Revision ID: 191301e58108
Revises: abc8437c0982
Create Date: 2026-03-06 18:18:35.219159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '191301e58108'
down_revision: Union[str, None] = 'abc8437c0982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_claim_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='claimstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_claim_requests_author_id'), 'author_claim_requests', ['author_id'], unique=False)
    op.create_index(op.f('ix_author_claim_requests_id'), 'author_claim_requests', ['id'], unique=False)
    op.create_index(op.f('ix_author_claim_requests_user_id'), 'author_claim_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_author_claim_requests_user_id'), table_name='author_claim_requests')
    op.drop_index(op.f('ix_author_claim_requests_id'), table_name='author_claim_requests')
    op.drop_index(op.f('ix_author_claim_requests_author_id'), table_name='author_claim_requests')
    op.drop_table('author_claim_requests')
    # ### end Alembic commands ###
