"""add paper_milestones

Revision ID: 1a179e75e008
Revises: 5db49c8a852f
Create Date: 2026-03-06 21:01:23.713284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a179e75e008'
down_revision: Union[str, None] = '5db49c8a852f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('milestone_type', sa.Enum('internal_deadline', 'submission', 'review', 'other', name='milestonetype'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_milestones_id'), 'paper_milestones', ['id'], unique=False)
    op.create_index(op.f('ix_paper_milestones_paper_id'), 'paper_milestones', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_milestones_paper_id'), table_name='paper_milestones')
    op.drop_index(op.f('ix_paper_milestones_id'), table_name='paper_milestones')
    op.drop_table('paper_milestones')
    # ### end Alembic commands ###
