"""add_author_dblp_pid

Revision ID: 29834d628b23
Revises: 41a91672f425
Create Date: 2026-03-08 23:17:55.670095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29834d628b23'
down_revision: Union[str, None] = '41a91672f425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('dblp_pid', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'authors', ['dblp_pid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='unique')
    op.drop_column('authors', 'dblp_pid')
    # ### end Alembic commands ###
