"""add_feature_flags

Revision ID: 37b89478e54c
Revises: 897b7506080e
Create Date: 2026-03-12 01:10:10.192948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37b89478e54c'
down_revision: Union[str, None] = '897b7506080e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user_feature_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['feature_key'], ['feature_flags.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'feature_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_feature_access')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
