"""add_author_orcid

Revision ID: 41a91672f425
Revises: 014a89866b74
Create Date: 2026-03-08 23:03:08.639102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a91672f425'
down_revision: Union[str, None] = '014a89866b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('orcid', sa.String(length=19), nullable=True))
    op.create_unique_constraint(None, 'authors', ['orcid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='unique')
    op.drop_column('authors', 'orcid')
    # ### end Alembic commands ###
