"""add_author_photo

Revision ID: 48fb36bf564c
Revises: 8ef55c68af9c
Create Date: 2026-03-07 00:38:18.387721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48fb36bf564c'
down_revision: Union[str, None] = '8ef55c68af9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('photo_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'photo_path')
    # ### end Alembic commands ###
