"""add due_date to todo_items

Revision ID: 5db49c8a852f
Revises: 191301e58108
Create Date: 2026-03-06 20:55:27.487814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db49c8a852f'
down_revision: Union[str, None] = '191301e58108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_items', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_items', 'due_date')
    # ### end Alembic commands ###
