"""add_group_review_exchange

Revision ID: 6881397ba0c4
Revises: 9fa82c7dc070
Create Date: 2026-03-06 23:50:00.606566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6881397ba0c4'
down_revision: Union[str, None] = '9fa82c7dc070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_review_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['research_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_review_balance')
    )
    op.create_index(op.f('ix_group_review_balances_group_id'), 'group_review_balances', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_review_balances_id'), 'group_review_balances', ['id'], unique=False)
    op.create_index(op.f('ix_group_review_balances_user_id'), 'group_review_balances', ['user_id'], unique=False)
    op.create_table('group_review_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'assigned', 'completed', 'cancelled', name='groupreviewrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['research_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_review_requests_group_id'), 'group_review_requests', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_review_requests_id'), 'group_review_requests', ['id'], unique=False)
    op.create_index(op.f('ix_group_review_requests_requester_id'), 'group_review_requests', ['requester_id'], unique=False)
    op.create_table('group_review_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['group_review_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_group_review_assignments_id'), 'group_review_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_group_review_assignments_reviewer_id'), 'group_review_assignments', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_review_assignments_reviewer_id'), table_name='group_review_assignments')
    op.drop_index(op.f('ix_group_review_assignments_id'), table_name='group_review_assignments')
    op.drop_table('group_review_assignments')
    op.drop_index(op.f('ix_group_review_requests_requester_id'), table_name='group_review_requests')
    op.drop_index(op.f('ix_group_review_requests_id'), table_name='group_review_requests')
    op.drop_index(op.f('ix_group_review_requests_group_id'), table_name='group_review_requests')
    op.drop_table('group_review_requests')
    op.drop_index(op.f('ix_group_review_balances_user_id'), table_name='group_review_balances')
    op.drop_index(op.f('ix_group_review_balances_id'), table_name='group_review_balances')
    op.drop_index(op.f('ix_group_review_balances_group_id'), table_name='group_review_balances')
    op.drop_table('group_review_balances')
    # ### end Alembic commands ###
