"""add_thesis_supervision

Revision ID: 897b7506080e
Revises: d554849fa310
Create Date: 2026-03-11 10:36:45.180039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897b7506080e'
down_revision: Union[str, None] = 'd554849fa310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervision_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('student_name', sa.String(length=255), nullable=True),
    sa.Column('student_email', sa.String(length=255), nullable=True),
    sa.Column('project_type', sa.Enum('masters_thesis', 'bachelors_thesis', 'master_project', 'seminar', name='supervisionprojecttype'), nullable=False),
    sa.Column('status', sa.Enum('incubating', 'ongoing', 'submitted', 'archived', name='supervisionstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('github_url', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervision_projects_id'), 'supervision_projects', ['id'], unique=False)
    op.create_index(op.f('ix_supervision_projects_supervisor_id'), 'supervision_projects', ['supervisor_id'], unique=False)
    op.create_table('supervision_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.Enum('expose', 'registration', 'draft', 'final', 'other', name='supervisiondocumenttype'), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['supervision_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervision_documents_id'), 'supervision_documents', ['id'], unique=False)
    op.create_index(op.f('ix_supervision_documents_project_id'), 'supervision_documents', ['project_id'], unique=False)
    op.create_table('supervision_type_workflow_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_type', sa.Enum('masters_thesis', 'bachelors_thesis', 'master_project', 'seminar', name='supervisionprojecttype'), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_type')
    )
    op.create_index(op.f('ix_supervision_type_workflow_configs_id'), 'supervision_type_workflow_configs', ['id'], unique=False)
    op.create_index(op.f('ix_supervision_type_workflow_configs_user_id'), 'supervision_type_workflow_configs', ['user_id'], unique=False)
    op.create_table('supervision_todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'done', name='todostatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source_workflow_step_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['supervision_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_workflow_step_id'], ['workflow_steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervision_todos_id'), 'supervision_todos', ['id'], unique=False)
    op.create_index(op.f('ix_supervision_todos_project_id'), 'supervision_todos', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supervision_todos_project_id'), table_name='supervision_todos')
    op.drop_index(op.f('ix_supervision_todos_id'), table_name='supervision_todos')
    op.drop_table('supervision_todos')
    op.drop_index(op.f('ix_supervision_type_workflow_configs_user_id'), table_name='supervision_type_workflow_configs')
    op.drop_index(op.f('ix_supervision_type_workflow_configs_id'), table_name='supervision_type_workflow_configs')
    op.drop_table('supervision_type_workflow_configs')
    op.drop_index(op.f('ix_supervision_documents_project_id'), table_name='supervision_documents')
    op.drop_index(op.f('ix_supervision_documents_id'), table_name='supervision_documents')
    op.drop_table('supervision_documents')
    op.drop_index(op.f('ix_supervision_projects_supervisor_id'), table_name='supervision_projects')
    op.drop_index(op.f('ix_supervision_projects_id'), table_name='supervision_projects')
    op.drop_table('supervision_projects')
    # ### end Alembic commands ###
