"""add_affiliation_logo

Revision ID: 8ef55c68af9c
Revises: a63ba12c6954
Create Date: 2026-03-07 00:34:39.846819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ef55c68af9c'
down_revision: Union[str, None] = 'a63ba12c6954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliations', sa.Column('logo_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliations', 'logo_path')
    # ### end Alembic commands ###
