"""add_group_wiki

Revision ID: 907f869d8055
Revises: e717f372b7fa
Create Date: 2026-03-07 14:02:56.112697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907f869d8055'
down_revision: Union[str, None] = 'e717f372b7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('locked_by_id', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['research_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locked_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'slug', name='uq_wiki_page_slug')
    )
    op.create_index(op.f('ix_wiki_pages_group_id'), 'wiki_pages', ['group_id'], unique=False)
    op.create_index(op.f('ix_wiki_pages_id'), 'wiki_pages', ['id'], unique=False)
    op.create_table('wiki_page_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('edited_by_id', sa.Integer(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('edit_note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['edited_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wiki_page_revisions_id'), 'wiki_page_revisions', ['id'], unique=False)
    op.create_index(op.f('ix_wiki_page_revisions_page_id'), 'wiki_page_revisions', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wiki_page_revisions_page_id'), table_name='wiki_page_revisions')
    op.drop_index(op.f('ix_wiki_page_revisions_id'), table_name='wiki_page_revisions')
    op.drop_table('wiki_page_revisions')
    op.drop_index(op.f('ix_wiki_pages_id'), table_name='wiki_pages')
    op.drop_index(op.f('ix_wiki_pages_group_id'), table_name='wiki_pages')
    op.drop_table('wiki_pages')
    # ### end Alembic commands ###
