"""add_paper_published_date

Revision ID: 97ad273a8684
Revises: e3b226a2af2a
Create Date: 2026-03-07 22:59:18.621478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ad273a8684'
down_revision: Union[str, None] = 'e3b226a2af2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_projects', sa.Column('published_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_projects', 'published_date')
    # ### end Alembic commands ###
