"""add service_records

Revision ID: 9fa82c7dc070
Revises: 1a179e75e008
Create Date: 2026-03-06 21:25:20.338599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa82c7dc070'
down_revision: Union[str, None] = '1a179e75e008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conference_edition_id', sa.Integer(), nullable=True),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('role', sa.Enum('reviewer', 'area_chair', 'senior_program_committee', 'program_chair', 'workshop_organizer', 'associate_editor', 'editor_in_chief', 'editorial_board', 'other', name='servicerole'), nullable=False),
    sa.Column('num_papers', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conference_edition_id'], ['conference_editions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_records_id'), 'service_records', ['id'], unique=False)
    op.create_index(op.f('ix_service_records_user_id'), 'service_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_records_user_id'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_id'), table_name='service_records')
    op.drop_table('service_records')
    # ### end Alembic commands ###
