"""add_group_logo

Revision ID: a63ba12c6954
Revises: 6881397ba0c4
Create Date: 2026-03-07 00:32:18.825340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63ba12c6954'
down_revision: Union[str, None] = '6881397ba0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_groups', sa.Column('logo_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_groups', 'logo_path')
    # ### end Alembic commands ###
