"""add_bibtex_collections

Revision ID: af0454cf57b7
Revises: 29834d628b23
Create Date: 2026-03-09 07:52:21.620356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af0454cf57b7'
down_revision: Union[str, None] = '29834d628b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bib_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('style', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bib_collections_id'), 'bib_collections', ['id'], unique=False)
    op.create_index(op.f('ix_bib_collections_owner_id'), 'bib_collections', ['owner_id'], unique=False)
    op.create_table('bib_collection_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['bib_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['research_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'group_id')
    )
    op.create_index(op.f('ix_bib_collection_shares_collection_id'), 'bib_collection_shares', ['collection_id'], unique=False)
    op.create_index(op.f('ix_bib_collection_shares_group_id'), 'bib_collection_shares', ['group_id'], unique=False)
    op.create_index(op.f('ix_bib_collection_shares_id'), 'bib_collection_shares', ['id'], unique=False)
    op.create_table('bib_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('cite_key', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('authors_raw', sa.Text(), nullable=True),
    sa.Column('fields_json', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['bib_collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'cite_key')
    )
    op.create_index(op.f('ix_bib_entries_collection_id'), 'bib_entries', ['collection_id'], unique=False)
    op.create_index(op.f('ix_bib_entries_id'), 'bib_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bib_entries_id'), table_name='bib_entries')
    op.drop_index(op.f('ix_bib_entries_collection_id'), table_name='bib_entries')
    op.drop_table('bib_entries')
    op.drop_index(op.f('ix_bib_collection_shares_id'), table_name='bib_collection_shares')
    op.drop_index(op.f('ix_bib_collection_shares_group_id'), table_name='bib_collection_shares')
    op.drop_index(op.f('ix_bib_collection_shares_collection_id'), table_name='bib_collection_shares')
    op.drop_table('bib_collection_shares')
    op.drop_index(op.f('ix_bib_collections_owner_id'), table_name='bib_collections')
    op.drop_index(op.f('ix_bib_collections_id'), table_name='bib_collections')
    op.drop_table('bib_collections')
    # ### end Alembic commands ###
