"""add_bibtex_group_and_write_revokes

Revision ID: d554849fa310
Revises: af0454cf57b7
Create Date: 2026-03-09 08:28:54.931808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd554849fa310'
down_revision: Union[str, None] = 'af0454cf57b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bib_collection_write_revokes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['bib_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'user_id')
    )
    op.create_index(op.f('ix_bib_collection_write_revokes_collection_id'), 'bib_collection_write_revokes', ['collection_id'], unique=False)
    op.create_index(op.f('ix_bib_collection_write_revokes_id'), 'bib_collection_write_revokes', ['id'], unique=False)
    op.create_index(op.f('ix_bib_collection_write_revokes_user_id'), 'bib_collection_write_revokes', ['user_id'], unique=False)
    op.add_column('bib_collections', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bib_collections_group_id'), 'bib_collections', ['group_id'], unique=False)
    op.create_foreign_key(None, 'bib_collections', 'research_groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bib_collections', type_='foreignkey')
    op.drop_index(op.f('ix_bib_collections_group_id'), table_name='bib_collections')
    op.drop_column('bib_collections', 'group_id')
    op.drop_index(op.f('ix_bib_collection_write_revokes_user_id'), table_name='bib_collection_write_revokes')
    op.drop_index(op.f('ix_bib_collection_write_revokes_id'), table_name='bib_collection_write_revokes')
    op.drop_index(op.f('ix_bib_collection_write_revokes_collection_id'), table_name='bib_collection_write_revokes')
    op.drop_table('bib_collection_write_revokes')
    # ### end Alembic commands ###
