"""add_notebook

Revision ID: e717f372b7fa
Revises: f666621d69f3
Create Date: 2026-03-07 13:48:15.276698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e717f372b7fa'
down_revision: Union[str, None] = 'f666621d69f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebook_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_notebook_tag')
    )
    op.create_index(op.f('ix_notebook_tags_id'), 'notebook_tags', ['id'], unique=False)
    op.create_index(op.f('ix_notebook_tags_user_id'), 'notebook_tags', ['user_id'], unique=False)
    op.create_table('notebook_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('conference_id', sa.Integer(), nullable=True),
    sa.Column('map_x', sa.Float(), nullable=True),
    sa.Column('map_y', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebook_entries_id'), 'notebook_entries', ['id'], unique=False)
    op.create_index(op.f('ix_notebook_entries_user_id'), 'notebook_entries', ['user_id'], unique=False)
    op.create_table('notebook_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['notebook_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['notebook_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebook_edges_id'), 'notebook_edges', ['id'], unique=False)
    op.create_index(op.f('ix_notebook_edges_source_id'), 'notebook_edges', ['source_id'], unique=False)
    op.create_index(op.f('ix_notebook_edges_target_id'), 'notebook_edges', ['target_id'], unique=False)
    op.create_table('notebook_entry_shares',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['notebook_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['research_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id', 'group_id')
    )
    op.create_table('notebook_entry_tags',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['notebook_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['notebook_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notebook_entry_tags')
    op.drop_table('notebook_entry_shares')
    op.drop_index(op.f('ix_notebook_edges_target_id'), table_name='notebook_edges')
    op.drop_index(op.f('ix_notebook_edges_source_id'), table_name='notebook_edges')
    op.drop_index(op.f('ix_notebook_edges_id'), table_name='notebook_edges')
    op.drop_table('notebook_edges')
    op.drop_index(op.f('ix_notebook_entries_user_id'), table_name='notebook_entries')
    op.drop_index(op.f('ix_notebook_entries_id'), table_name='notebook_entries')
    op.drop_table('notebook_entries')
    op.drop_index(op.f('ix_notebook_tags_user_id'), table_name='notebook_tags')
    op.drop_index(op.f('ix_notebook_tags_id'), table_name='notebook_tags')
    op.drop_table('notebook_tags')
    # ### end Alembic commands ###
