"""add_suggestions_and_moderator

Revision ID: f666621d69f3
Revises: 48fb36bf564c
Create Date: 2026-03-07 11:41:27.604716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f666621d69f3'
down_revision: Union[str, None] = '48fb36bf564c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('conference', 'conference_edition', 'journal', 'journal_special_issue', name='suggestiontype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='suggestionstatus'), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestions_id'), 'suggestions', ['id'], unique=False)
    op.create_index(op.f('ix_suggestions_status'), 'suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_suggestions_submitted_by_id'), 'suggestions', ['submitted_by_id'], unique=False)
    op.add_column('users', sa.Column('is_moderator', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_moderator')
    op.drop_index(op.f('ix_suggestions_submitted_by_id'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_status'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_id'), table_name='suggestions')
    op.drop_table('suggestions')
    # ### end Alembic commands ###
